site_name: 'Tutorial of <span style=''color:#d6604d''> GEIGER</span> Indicator'
site_url: 'https://ngsi-ld.tutorials.readthedocs.org'
site_description: GEIGER indicator Tutorial Documentation
theme: readthedocs
nav:
  - Home: index.md
  - GEIGER Risk Score: geiger-risk-score.md
  - GEIGER Indicator Algorithm: indicator-algorithm.md
  - GEIGER Data for Risk Score:
    - ':Local' : 'data/local.md'
    - ':Global' : 'data/global.md'
    - ':Enterpise' : 'data/enterprise.md'
    - ':Devices' : 'data/devices.md'
    - 'sensor values' : 'data/sensor-values.md'
    - 'geigerScore' : 'data/geiger-score.md'
    - 'geigerRecommendation' : 'data/recommendation.md'
  - Implementation:
    - 'System Architecture': 'imple/system-architecture.md'
    - 'Flowchart': 'imple/flowchart.md'
    - 'Source Code': 'imple/source-code.md'
  - Test case:
    - 'Get instance of Local Data Storage': 'testcase/1-accessLDS.md'
    - 'Get current user and device UUID': 'testcase/2-getuuid.md'
    - 'Prepare indicator input data': 'testcase/prepare-inputdata.md'
    - 'Check risk score nodes exist': 'testcase/4-checkdataexist.md'
    - 'Recived notification of GEIGER data': 'testcase/listen-geiger-data.md'
    - 'Score Calculation' : 'testcase/scoreCalculation.md'
